trigger: none

variables:
- name: devEnvironment
  value: dev

resources:
  pipelines:
  - pipeline: ciPipeline
    source: 'Classic - CI'
    trigger:
      branches:
      - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/vars-iac.yml
  - template: variables/vars-ci.yml
  - template: variables/vars-cd.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-18.04
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: '$(devServiceConnection)'
              appType: 'functionApp'
              appName: '$(logicAppName)'
              package: '$(Pipeline.Workspace)/ciPipeline/$(logicAppCIArtifactName)/$(publishOutputFolder).zip'
              appSettings: '-emailAddress $(toEmailAddress) -iotTopic $(topic) -iotMessageSubject $(iotMessageSubject) -iotHubPath $(iotHubPath)'
              deploymentMethod: 'zipDeploy'
