trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

variables:
- name: workingDirectory
  value: $(System.DefaultWorkingDirectory)
- template: variables/vars-ci.yml
- template: variables/vars-iac.yml

jobs:
- job: logic_app_build
  displayName: 'Build and publish logic app'
  steps:
  - task: PowerShell@2
    displayName: 'Generate connections.json file'
    inputs:
      filePath: '$(workingDirectory)/.pipelines/scripts/Generate-Connections.ps1'
      arguments: '-resourceGroup $(resourceGroupName)'

  - template: templates/template-build-logicapp.yml
    parameters:
      workingDirectory: $(workingDirectory)
      configuration: Release
      outputFolder: $(publishOutputFolder)

  - task: PublishPipelineArtifact@1
    displayName: 'Publish pipeline artifact'
    inputs:
      targetPath: '$(workingDirectory)/$(publishOutputFolder)'
      artifact: '$(logicAppCIArtifactName)'
      publishLocation: 'pipeline'
