trigger:
- main

pr: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
- name: workingDirectory
  value: $(System.DefaultWorkingDirectory)
- template: variables/vars-iac.yml
- template: variables/vars-ci.yml
# TODO: You can remove this. Only in place for the sample AzDO pipeline.
- group: azure_subscription

jobs:
- job: logic_app_build
  displayName: 'Build and publish logic app'
  steps:
  - task: PowerShell@2
    displayName: 'Generate connections.json file'
    inputs:
      filePath: '$(workingDirectory)/.pipelines/scripts/Generate-Connections.ps1'
      arguments: '-resourceGroup $(resourceGroupName)'

  - task: AzureCLI@2
    displayName: 'Build & Push Logic App Image'
    inputs:
      azureSubscription: $(devServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr build \
        -r $(acrName) \
        -t $(logicAppContainerName):$(Build.BuildId) \
        -t $(logicAppContainerName):latest \
        .
      workingDirectory: $(workingDirectory)
