trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

variables:
- name: workingDirectory
  value: $(System.DefaultWorkingDirectory)
- template: variables/vars-iac.yml
- template: variables/vars-ci.yml
# TODO: You can remove this. Only in place for the sample AzDO pipeline.
- group: azure_subscription

jobs:
- job: logic_app_build
  displayName: 'Build and publish logic app'
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download connector deployment output file'
    inputs:
      source: 'specific'
      project: '$(projectId)'
      definition: '$(iacPipelineDefinitionId)'
      runVersion: 'latest'
      targetPath: '$(Pipeline.Workspace)'

  - task: PowerShell@2
    displayName: 'Populate connections.json file with parameters'
    inputs:
      filePath: '$(workingDirectory)/.pipelines/scripts/Configure-Connections.ps1'
      arguments: '-armOutputFilePath $(Pipeline.Workspace)/$(logicAppIacOutputArtifactName)/$(connectorOutputFileName)
      -connectionsFilePath connections.devops.json
      -outputLocation connections.json'

  - task: AzureCLI@2
    displayName: 'Build & Push Logic App Image'
    inputs:
      azureSubscription: $(devServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr build \
        -r $(acrName) \
        -t $(logicAppContainerName):$(Build.BuildId) \
        -t $(logicAppContainerName):latest \
        .
      workingDirectory: $(workingDirectory)
